"""Render the SDK result discriminator from its sole receiving declaration."""
import json
from pathlib import Path

from agent_comms.field_codec import FieldCodec
from agent_comms.native_file_artifact import Utf8FileWriteArtifact
from agent_comms.pi_payloads import FileMutationToolDetails, NativeToolDetails


def main():
    contract = {
        "discriminator": NativeToolDetails.wire_tag,
        "details_name": FileMutationToolDetails.declared_name,
        "artifact_field": next(wire for field, wire in FieldCodec._fields(FileMutationToolDetails)
                               if field.name == "artifact"),
        "artifact_name": Utf8FileWriteArtifact.declared_name,
    }
    target = Path(__file__).resolve().parents[1] / "stack/native-file-artifact-schema.mjs"
    target.write_text(
        "// Generated by tools/render_native_file_artifact_schema.py; declarations own this contract.\n"
        + "export const nativeFileArtifactSchema = " + json.dumps(contract, indent=2) + ";\n")


if __name__ == "__main__":
    main()
