"""Render the native proof writer schema from its sole Python row declaration."""

import json
from pathlib import Path

from agent_comms.native_pi import NativeContextJournal


def main() -> None:
    target = Path(__file__).resolve().parents[1] / "stack/native-proof-schema.mjs"
    target.write_text(
        "// Generated by tools/render_native_proof_schema.py; NativeContextJournal owns this contract.\n"
        "export const nativeProofSchema = "
        + json.dumps(NativeContextJournal.native_contract(), indent=2)
        + ";\n"
    )


if __name__ == "__main__":
    main()
